<template>
  <v-app>
    <v-navigation-drawer app v-model="drawer" temporary flat>
      <!-- -->
    </v-navigation-drawer>

    <v-app-bar app absolute flat color="primary">
      <!--     <v-app-bar-nav-icon @click.stop="drawer = !drawer"></v-app-bar-nav-icon>  -->
      <v-app-bar-title shrink-on-scroll>
        <Title class="tracking-in-expand" />
      </v-app-bar-title>
      <v-spacer></v-spacer>
      <v-btn text>Home</v-btn>
      <v-btn text>CV</v-btn>
    </v-app-bar>

    <v-main>
      <v-container fluid>
        <router-view></router-view>
      </v-container>
    </v-main>

    <v-footer app padless absolute>
      <Footer />
    </v-footer>
  </v-app>
</template>

<script>
import Footer from "@/components/layout/Footer.vue";
import Title from "@/components/layout/Title.vue";

export default {
  name: "App",

  components: {
    Footer,
    Title,
  },

  data: () => ({
    drawer: null,
  }),
};
</script>

<style>
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1)
    both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-21 18:0:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
</style>
